// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Alianza.Models
{
    public partial class Request
    {
        public int Id { get; set; }
        public DateTime Date { get; set; }
        public bool Status { get; set; }
        public string Type { get; set; }
        public string Email { get; set; }
        public DateTime? ApplyDate { get; set; }
        public DateTime? EndDate { get; set; }
        public bool Undefined { get; set; }
        public string Shift { get; set; }
        public string OperationalManager { get; set; }
        public bool AuthorizeOperational { get; set; }
        public string Hr { get; set; }
        public bool AuthorizeHr { get; set; }
        public string ItManager { get; set; }
        public bool AuthorizeIt { get; set; }
        public string GeneralManager { get; set; }
        public bool AuthorizeGeneral { get; set; }
        public string EmailNew { get; set; }

        public virtual User EmailNavigation { get; set; }
    }
}