// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Alianza.Models
{
    public partial class User
    {
        public User()
        {
            AccountNumbers = new HashSet<AccountNumber>();
            AccountingAccounts = new HashSet<AccountingAccount>();
            ExclusiveData = new HashSet<ExclusiveData>();
            Requests = new HashSet<Request>();
        }

        public int Id { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public string Position { get; set; }
        public string Profile { get; set; }
        public string Branch { get; set; }

        public virtual ICollection<AccountNumber> AccountNumbers { get; set; }
        public virtual ICollection<AccountingAccount> AccountingAccounts { get; set; }
        public virtual ICollection<ExclusiveData> ExclusiveData { get; set; }
        public virtual ICollection<Request> Requests { get; set; }
    }
}